In [11]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse

In [ ]:
a = [(16,2),(10,5),(2,2), (7,1)]
每个tuple里第一个数是这本书的价格，第二个数是这本书的重量。
假设你有18的credit，如何选出两本书的价格能用尽可能多的credit的同时重量还是相对最少的。属于一道two sum的变种吧

In [44]:
a = [(16,2),(10,5),(2,2), (7,1), (2,1), (16,1)]


In [45]:
total_weight = 10000
total_credit = 0
book = ()

for i in range(0, len(a)):
    for j in range(i+1, len(a)):
        if (a[i][0] <= 18) & (a[j][0] <= 18):
            temp_credit = a[i][0] + a[j][0]
            temp_weight = a[i][1] + a[j][1]
            if (temp_credit <= 18) & (temp_credit > total_credit):
                total_credit = temp_credit
                total_weight = total_weight
                book = (i,j)
            elif (temp_credit <= 18) & (temp_credit == total_credit) & (temp_weight < total_weight):
                total_credit = temp_credit
                total_weight = total_weight
                book = (i,j)
print (book        )

(4, 5)


In [14]:
A =  np.array([[0, 1, 0, 0, 1], [0, 0, 1, 1, 1],[1, 1, 0, 1, 0]])
A_sparse = sparse.csr_matrix(A)
print(A_sparse)

  (0, 1)	1
  (0, 4)	1
  (1, 2)	1
  (1, 3)	1
  (1, 4)	1
  (2, 0)	1
  (2, 1)	1
  (2, 3)	1


In [16]:
similarities = cosine_similarity(A_sparse)
print('pairwise dense output:\n {}\n'.format(similarities))

#also can output sparse matrices
similarities_sparse = cosine_similarity(A_sparse,dense_output=False)
print('pairwise sparse output:\n {}\n'.format(similarities_sparse))

pairwise dense output:
 [[1.         0.40824829 0.40824829]
 [0.40824829 1.         0.33333333]
 [0.40824829 0.33333333 1.        ]]

pairwise sparse output:
   (0, 1)	0.408248290463863
  (0, 2)	0.408248290463863
  (0, 0)	0.9999999999999998
  (1, 0)	0.408248290463863
  (1, 2)	0.3333333333333334
  (1, 1)	1.0000000000000002
  (2, 1)	0.3333333333333334
  (2, 0)	0.408248290463863
  (2, 2)	1.0000000000000002



In [17]:
similarities = cosine_similarity(A)
print('pairwise dense output:\n {}\n'.format(similarities))

#also can output sparse matrices
similarities_sparse = cosine_similarity(A,dense_output=False)
print('pairwise sparse output:\n {}\n'.format(similarities_sparse))

pairwise dense output:
 [[1.         0.40824829 0.40824829]
 [0.40824829 1.         0.33333333]
 [0.40824829 0.33333333 1.        ]]

pairwise sparse output:
 [[1.         0.40824829 0.40824829]
 [0.40824829 1.         0.33333333]
 [0.40824829 0.33333333 1.        ]]



In [152]:
similarities[0,2]

0.408248290463863

In [ ]:
"""
column A: string, numeric, numeric
column B: categorical, numeric, string
column C: string, string, string
column D: numeric, numeric, numeric
"""

写一个func输出只含有某一种type的column，
比如
get_columm(input_str, 'numeric')
需要输出 column D
get_columm(input_str, 'string')
需要输出 column C

follow up 是如果是多重types的，选出包含任意其中任意一种type的columns；
记得好像还有选出满足其中所有types的columns
例如
get_column(input_str, ['string, numeric'])
需要输出 column A。

In [48]:
A = '''column A: string, numeric, numeric
column B: categorical, numeric, string
column C: string, string, string
column D: numeric, numeric, numeric'''

In [59]:
def get_column(string, input_type):
    for i in string.splitlines():
        column_type = set(i[10:].split(', '))
        if ({input_type} == column_type) & (len(column_type) == 1):
            print (i[0:8])

In [61]:
get_column(A, 'numeric')

column D


In [64]:
def get_column(string, input_type):
    for i in string.splitlines():
        column_type = set(i[10:].split(', '))
        if (input_type[0] in column_type) | (input_type[1] in column_type):
            print (i[0:8])

In [66]:
get_column(A, ['string', 'numeric'])

column A
column B
column C
column D


In [67]:
def get_column(string, input_type):
    for i in string.splitlines():
        column_type = set(i[10:].split(', '))
        if (input_type[0] in column_type) & (input_type[1] in column_type):
            print (i[0:8])

In [68]:
get_column(A, ['string', 'numeric'])

column A
column B


In [ ]:
就一个简单的coding 问题，一个list，e.g.[0,1,1,0...] 用0,1来定义water和ship, 让找出船头和船尾的index，
开始一问只有一艘船，后来follow up有多艘的情况，要考虑各种 edge cases，code要能跑，然后有问题要debug

In [87]:
a = [0,1,1,1,0]

def ship(lst):
    first = -1
    end = -1
    for i, j in enumerate(lst):
        if j == 1:
            if first == -1:
                first = i
        if j == 0:
            if first != -1:
                end = i-1
    print(first, end)
ship(a)        
            

1 3


In [121]:
a = [0,1,1,1,0,0,1,1,0,1,1,1,1,0]
def ship(lst):
    ship = dict()
    cnt = 0
    for index, j in enumerate(lst):
        if j == 1:
            if (cnt not in ship):
                cnt += 1
                ship[cnt] = {'first': index}
            elif ('end' in ship[cnt]):
                cnt += 1
                ship[cnt] = {'first': index}
        if j == 0:
            if cnt in ship:
                ship[cnt].update({'end': index-1})
    print(ship)
ship(a)        
            

{1: {'first': 1, 'end': 4}, 2: {'first': 6, 'end': 7}, 3: {'first': 9, 'end': 12}}


In [ ]:
给你一个strings 都是字母 确保这个string的数字是最大. 
让你把字母设置一个数字 每个字母可以代表一个数字 但是需要你能把这个string 返还最大的和
反正本意就是希望你首先把字母出现的频率算出来 再把频率最高的设置最大的数字 这样返还的和就是最大的
需要你return这个和

In [46]:
a = 'ascscefwaassfe'
letters = set(a)
value = dict()
for i in letters:
    value[i] = a.count(i)
rank = list(range(1,len(value.keys())+1))
rank = [10-i for i in rank]
new_value = dict(zip(sorted(value, key=value.get, reverse=True), rank))
total = 0
for i in value.keys():
    total = total+value[i]*new_value[i]
print(total)

['s', 'a', 'f', 'c', 'e', 'w']

In [ ]:

 和Markov Chain 相关的一题，一个input是string like "The sky is blue, the tree is green, the lake is blue."
    另一个input是这个string里的某一个word，比如“is”. 
    return 一个word，要求：
1. 这个word是在那个input word 之后
2. with prob 出现的次数出现

例如， is后面可以是[blue，green，blue]。所以要以2/3的概率return blue，1/3的概率return green。

我有思路，但是写了80%但是时间不够没有写，就没有给过。 附上自己后来重新写的答案（就是大概写了一下，如果有哪处不对请指正），希望对大家有帮助。


sts = "The sky is blue, the tree is green. The lake is blue"
word = "is"

from random import random

def func(sts, word):
    sts = sts.strip().lower()
    sts = sts.replace(',', '')
    sts = sts.replace('.', '')
    sts = sts.split()

    n = len(sts)
    dict0 = {item: {} for item in sts}
    for i in range(n-1):
        if sts[i+1] in dict0[sts[i]].keys():
            dict0[sts[i]][sts[i+1]] +=1
        else:
            dict0[sts[i]][sts[i+1]] = 1

    rand = random()
    ref = helper(dict0[word])

    for item in ref:
        if item[1][0]<= rand < item[1][1]:
            return item[0]

    return None


def helper(dict0):
    sum0 = sum(dict0.values())

    temp = 0
    ref =[]
    for key,val in dict0.items():
        ref.append((key,[temp, temp+val/sum0]))
        temp += val/sum0

    return ref


print(func(sts, 'is'))
print(func(sts, 'is'))
print(func(sts, 'is'))
print(func(sts, 'is'))
print(func(sts, 'is'))
print(func(sts, 'is'))
print(func(sts, 'is'))
print(func(sts, 'is'))
print(func(sts, 'is'))

In [109]:
sts = "The sky is blue, the tree is green. The lake is blue"
word = "is"
import re
re.split("[, \-!?:]+", sts)

['The',
 'sky',
 'is',
 'blue',
 'the',
 'tree',
 'is',
 'green.',
 'The',
 'lake',
 'is',
 'blue']

In [119]:
sts = sts.replace(",", "")
sts = sts.replace(".", "")
lst = sts.split()
final_lst = []
for i,j in enumerate(lst):
    if j=='is':
        final_lst.append(lst[i+1])
print(final_lst)
temp_dict = dict()
final_dict = dict()
temp = 0
for i in final_lst:
    temp_dict[i] = final_lst.count(i)/len(final_lst)
for i in temp_dict.keys():
    final_dict[i] = [temp, temp+temp_dict[i]]
    temp = temp+temp_dict[i]

print(final_dict)


from random import random
num = random()
print(num)
def return_word(num):
    for i in final_dict.keys():
        if (num >= final_dict[i][0]) & (num <= final_dict[i][1]):
            print(i)
return_word(num)

['blue', 'green', 'blue']
{'blue': [0, 0.6666666666666666], 'green': [0.6666666666666666, 1.0]}
0.4598407700831134
blue


In [85]:
from random import random

def func(sts, word):
    sts = sts.strip().lower()
    sts = sts.replace(',', '')
    sts = sts.replace('.', '')
    sts = sts.split()

    n = len(sts)
    dict0 = {item: {} for item in sts}
    for i in range(n-1):
        if sts[i+1] in dict0[sts[i]].keys():
            dict0[sts[i]][sts[i+1]] +=1
        else:
            dict0[sts[i]][sts[i+1]] = 1

    rand = random()
    print(rand)
    print(dict0)
    ref = helper(dict0[word])
    print(ref)

    for item in ref:
        if item[1][0]<= rand < item[1][1]:
            return item[0]

    return None


def helper(dict0):
    sum0 = sum(dict0.values())
    print(sum0)
    temp = 0
    ref =[]
    for key,val in dict0.items():
        print(ref)
        ref.append((key,[temp, temp+val/sum0]))
        temp += val/sum0

    return ref


func(sts, word)

0.10641594950148958
{'the': {'sky': 1, 'tree': 1, 'lake': 1}, 'sky': {'is': 1}, 'is': {'blue': 2, 'green': 1}, 'blue': {'the': 1}, 'tree': {'is': 1}, 'green': {'the': 1}, 'lake': {'is': 1}}
3
[]
[('blue', [0, 0.6666666666666666])]
[('blue', [0, 0.6666666666666666]), ('green', [0.6666666666666666, 1.0])]


'blue'